module.exports = [{
		"type": 0,
		"name": "兴趣艺术",
		"click": 0,
		"secondary": [{
			"type": 0,
			"code": "KR",
			"name": "美术",
			"click": 0,
			"international": 1,
			"zones": [{
				"type": 4,
				"code": "SEL",
				"name": "素描",
				"click": 1,
				"international": 1
			}, {
				"type": 4,
				"code": "CJU",
				"name": "彩绘",
				"click": 1,
				"international": 1
			}, {
				"type": 4,
				"code": "PUS",
				"name": "水彩",
				"click": 1,
				"international": 1
			}, {
				"type": 4,
				"code": "CJJ",
				"name": "油画",
				"click": 1,
				"international": 1
			}, {
				"type": 4,
				"code": "TAE",
				"name": "手绘",
				"click": 1,
				"international": 1
			}, {
				"type": 4,
				"code": "USN",
				"name": "国画",
				"click": 1,
				"international": 1
			}, {
				"type": 4,
				"code": "RSU",
				"name": "书法",
				"click": 1,
				"international": 1
			}]
		}, {
			"type": 0,
			"code": "JP",
			"name": "音乐",
			"click": 0,
			"international": 1,
			"zones": [{
				"type": 4,
				"code": "OSA",
				"name": "钢琴",
				"click": 1,
				"international": 1
			}, {
				"type": 4,
				"code": "TYO",
				"name": "吉他",
				"click": 1,
				"international": 1
			}, {
				"type": 4,
				"code": "SPK",
				"name": "声乐",
				"click": 1,
				"international": 1
			}, {
				"type": 4,
				"code": "KIJ",
				"name": "古筝",
				"click": 1,
				"international": 1
			}, {
				"type": 4,
				"code": "TOY",
				"name": "说唱",
				"click": 1,
				"international": 1
			}, {
				"type": 4,
				"code": "IBR",
				"name": "声乐演唱",
				"click": 1,
				"international": 1
			}, {
				"type": 4,
				"code": "MYJ",
				"name": "架子鼓",
				"click": 1,
				"international": 1
			}, {
				"type": 4,
				"code": "NGS",
				"name": "国乐",
				"click": 1,
				"international": 1
			}]
		}],
		"international": 1
	},
	{
		"type": 0,
		"name": "设计创作",
		"click": 0,
		"secondary": [{
			"type": 0,
			"code": "KR",
			"name": "视觉设计",
			"click": 0,
			"international": 1,
			"zones": [{
				"type": 4,
				"code": "SEL",
				"name": "平面设计",
				"click": 1,
				"international": 1
			}, {
				"type": 4,
				"code": "CJU",
				"name": "UI设计",
				"click": 1,
				"international": 1
			}, {
				"type": 4,
				"code": "PUS",
				"name": "形象设计",
				"click": 1,
				"international": 1
			}, {
				"type": 4,
				"code": "CJJ",
				"name": "服装设计",
				"click": 1,
				"international": 1
			}, {
				"type": 4,
				"code": "TAE",
				"name": "汉服设计",
				"click": 1,
				"international": 1
			}, {
				"type": 4,
				"code": "USN",
				"name": "海报设计",
				"click": 1,
				"international": 1
			}, {
				"type": 4,
				"code": "RSU",
				"name": "淘宝美工",
				"click": 1,
				"international": 1
			}]
		}, {
			"type": 0,
			"code": "JP",
			"name": "游戏动漫",
			"click": 0,
			"international": 1,
			"zones": [{
				"type": 4,
				"code": "OSA",
				"name": "游戏模型",
				"click": 1,
				"international": 1
			}, {
				"type": 4,
				"code": "TYO",
				"name": "游戏特效",
				"click": 1,
				"international": 1
			}, {
				"type": 4,
				"code": "SPK",
				"name": "动画设计",
				"click": 1,
				"international": 1
			}, {
				"type": 4,
				"code": "KIJ",
				"name": "插画",
				"click": 1,
				"international": 1
			}, {
				"type": 4,
				"code": "TOY",
				"name": "富山",
				"click": 1,
				"international": 1
			}, {
				"type": 4,
				"code": "IBR",
				"name": "插画",
				"click": 1,
				"international": 1
			}, {
				"type": 4,
				"code": "MYJ",
				"name": "商务绘画",
				"click": 1,
				"international": 1
			}, {
				"type": 4,
				"code": "NGS",
				"name": "平板绘画",
				"click": 1,
				"international": 1
			}]
		}],
		"international": 1
	},
	{
		"type": 0,
		"name": "实用外语",
		"click": 0,
		"secondary": [{
			"type": 0,
			"code": "HK",
			"name": "英语",
			"click": 0,
			"international": 1,
			"zones": [{
				"type": 4,
				"code": "HKG",
				"name": "基础英语",
				"click": 1,
				"international": 1
			}, {
				"type": 4,
				"code": "HKG",
				"name": "英语口语",
				"click": 1,
				"international": 1
			}]
		}, {
			"type": 0,
			"code": "TW",
			"name": "日语",
			"click": 0,
			"international": 1,
			"zones": [{
				"type": 4,
				"code": "TPE",
				"name": "日语初级",
				"click": 1,
				"international": 1
			}, {
				"type": 4,
				"code": "KHH",
				"name": "日语中级",
				"click": 1,
				"international": 1
			}, {
				"type": 4,
				"code": "RMQ",
				"name": "日语高级",
				"click": 1,
				"international": 1
			}]
		}],
		"international": 1
	}
];
